services:
   db:
     platform: linux/x86_64
     image: mysql:8.3
     volumes:
       - ./mysql/data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     platform: linux/x86_64
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
     volumes:
       - ./themes/original-theme:/var/www/html/wp-content/themes/original-theme
       - ./wordpress-config/php.ini:/usr/local/etc/php/conf.d/uploads.ini
       - plugin_data:/var/www/html/wp-content/plugins:rw
       - upload_data:/var/www/html/wp-content/uploads:rw

   phpmyadmin:
      depends_on:
        - db
      platform: linux/x86_64
      image: phpmyadmin/phpmyadmin
      ports:
        - "8081:80"

volumes:
    db_data:
      driver: local
    plugin_data:
      driver: local
    upload_data:
      driver: local
