services:
   db:
     platform: linux/x86_64
     image: mysql:8.3
     volumes:
       - ./mysql/data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     platform: linux/x86_64
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./themes/original-theme:/var/www/html/wp-content/themes/original-theme
       - ./plugins:/var/www/html/wp-content/plugins
       - ./uploads:/var/www/html/wp-content/uploads
       - ./wordpress-config/php.ini:/usr/local/etc/php/conf.d/uploads.ini

   phpmyadmin:
      depends_on:
        - db
      platform: linux/x86_64
      image: phpmyadmin/phpmyadmin
      ports:
        - "8081:80"

volumes:
    db_data: {}